### ISSUE TITLE
Support for Next.js dynamic import

### ISSUE THREAD

**Issue by navin-moorthy** [webpro/knip#103]
Components imported using Next.js dynamic import is reported as unused export.

```javascript
const Component = dynamic(() =>
	import("./Component").then((module) => module.Component),
);
```

**Comment by webpro** [comment]
Dynamic imports should work, do you have a reproducible test case I can look at?

**Comment by navin-moorthy** [comment]
Oh, then let me create a reproduction repo.

**Comment by navin-moorthy** [comment]
Here is the reproduction codesandbox - https://codesandbox.io/p/sandbox/optimistic-colden-uuhvyo?file=%2Fsrc%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A13%7D%5D

Open the terminal & run `pnpm knip --production` to see the unused export as shown below,

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/39694575/228446311-187730b6-d85e-4f2c-bc92-0871a2e054b1.png">

**Comment by webpro** [comment]
Thanks @navin-moorthy!

It turned out that the combination of dynamic import + `then()` + referring to a specific export was indeed not covered by Knip, and tricky. Figured out that it is understood properly by TypeScript only when `"compilerOptions: { "types": ["node"] }` and/or `/// <reference types="node" />` is present, guess that's why I missed it earlier on.

Anyway, it should be fixed in [v2.2.1](https://github.com/webpro/knip/releases/tag/2.2.1).

Just saying, whatever is less work for you, a link to a repo with a reproducible case would work as well (otherwise I'd need to fork anyway since I need to debug inside Knip source code which isn't possible/feasible inside CSB).

**Comment by navin-moorthy** [comment]
Oh that a quick fix !

I thought a csb like will be useful - actually I cloned this [repo](https://github.com/timelessco/next-react-app) in csb for this reproduction.

**Comment by webpro** [comment]
> Oh that a quick fix !

🤠

> I thought a csb like will be useful - actually I cloned this [repo](https://github.com/timelessco/next-react-app) in csb for this reproduction.

I guess it depends a bit on the issue. To debug Knip issues I often use the Node.js inspector locally with VS Code for breakpoints etc and CSB is not optimal for that I think. I think I was not allowed to run commands in the CSB terminal without forking it.

**Comment by navin-moorthy** [comment]
I am still seeing some dynamic exports listed, let me provide you the repo.

**Comment by navin-moorthy** [comment]
I was able to find the issue by myself, since I cannot reproduce it in a reproduction repo.

Here is the sceneria,

- I have a type import - this is obviously not dynamic.

```sh
🚀 ~ file: index.js:194 ~ analyzeSourceFile ~ specifierFilePath: /Users/dialog/HeaderMenuDialogContent.tsx
🚀 ~ file: index.js:182 ~ analyzeSourceFile ~ importItems: {
  specifier: './HeaderMenuDialogContent',
  isStar: false,
  isReExported: false,
  isReExportedBy: Set(0) {},
  symbols: Set(1) { 'HeaderMenuDialogContentProps' },
  isDynamic: false
}
```
- I have a component import elsewhere which is a dynamic import

```sh
🚀 ~ file: index.js:194 ~ analyzeSourceFile ~ specifierFilePath: /Users/dialog/HeaderMenuDialogContent.tsx
🚀 ~ file: index.js:182 ~ analyzeSourceFile ~ importItems: {
  specifier: './HeaderMenuDialogContent',
  isStar: false,
  isReExported: false,
  isReExportedBy: Set(0) {},
  symbols: Set(1) { '__anonymous' },
  isDynamic: true
}
```

- When merging two `importedSymbols`, we were not merging the `isDynamic`.
<img width="990" alt="Screenshot 2023-03-30 at 1 12 35 PM" src="https://user-images.githubusercontent.com/39694575/228766055-a0d646f3-cac9-4ed9-9748-412c4d949bd7.png">

- This causes `isDynamic` to be always `false` which then later gets excluded here eventhough the actual import is dynamic & the type import which is not dynamic.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/39694575/228766705-ade2cfc5-9afc-4eb3-a311-32b3ba260798.png">

**NOTE:** Just my thought, would adding a new object like `isType` in `importItems` & `exportItems` be helpful to classify imports & exports instead of merging them?

**Comment by navin-moorthy** [comment]
Any thoughts on this ?

Would adding a new object like isType in importItems & exportItems be helpful to classify imports & exports instead of merging them?

**Comment by webpro** [comment]
Thanks for raising your concerns. Could you please elaborate on where or how are they merged?

- In `getImportsAndExports` there are separate `addImport` and `addExport` functions for AST visitors.
- The `exportedSymbols` and `importedSymbols` are collected separately for all files.
- And eventually `exportedSymbols` is iterated over to find unused exports.

**Comment by webpro** [comment]
Ah sorry, I think I misunderstood. You meant that imported items (`importItems`) can be re-exported, right?

The way it is currently organized, is optimized for a fast iteration of `exportedSymbols` to find out whether the export is imported anywhere, or when it is a re-export or star import to file it under unused `nsExports`, etc. etc., while minimizing the use of `principal.hasExternalReferences` as that uses the (potentially) expensive `findReferences` of the TS language service. And yes, types are included here as well.

By all means, if you have ideas, feel free to explore and experiment. It's still very early days for this project and I'd be happy to have more eyes on it and improvements are always welcome!

**Comment by webpro** [comment]
Oh, dumb me. Now I finally get it. That `type` is already there in the exported symbols. You can look for `SymbolType`. I think it's only necessary in exports, which are eventually used to report to the user. Although this is far from complete, it's not always easy to get this from the AST during traversal.

**Comment by navin-moorthy** [comment]
>Oh, dumb me. Now I finally get it. That type is already there in the exported symbols. You can look for SymbolType. I think it's only necessary in exports, which are eventually used to report to the user.

Ha, I missed it. 👌 

>  Although this is far from complete, it's not always easy to get this from the AST during traversal.

Yeah I feel the pain.

Anyhow great work 💪 , hope to contribute more in free time.
