### ISSUE TITLE
Handle `jsx: react-jsx` and `jsx: react-jsxdev` in `tsconfig.json`

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#186]
In these modes React becomes an implicit runtime dependency when any JSX is encountered, see [`jsx`](https://www.typescriptlang.org/tsconfig#jsx).

There's also a related option, [`jsxImportSource`](https://www.typescriptlang.org/tsconfig#jsxImportSource), which replaces React with something else. For example, in our case it's `jsxImportSource: hastscript/svg`, so then it's `hastscript` instead of `react`. One more consideration is that `jsxImportSource` can be overridden on per-file basis with pragmas, like so:

```ts
/** @jsxImportSource preact */
export const App = () => <h1>Hello World</h1>;
```

**Comment by webpro** [comment]
What is the issue you're encountering, getting false positives in unused dependencies, and which one(s)?

Would be great if you have a rep(r)o or something.

**Comment by alecmev** [comment]
Sure! https://github.com/alecmev/knip-repro-186

```
Unused files (1)
.yarn/releases/yarn-3.6.1.cjs
Unused dependencies (3)
@types/react  package.json
hastscript    package.json
react         package.json
```

There should be no "Unused dependencies".

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.18.0. See [Release 2.18.0](https://github.com/webpro/knip/releases/tag/2.18.0) for release notes._

**Comment by webpro** [comment]
Thanks for the report and the repro, helps a lot! Not 100% sure if this covers all forms of pragmas, but it's a start.

**Comment by alecmev** [comment]
Thank you! This doesn't cover `hastscript/svg`, unfortunately, as the whole string is added as a dependency, without trimming off the non-package stuff. This isn't a quirk of `hastscript` as it contains two runtimes, `html` and `svg`. This needs similar treatment to that of ESLint configs, where everything is removed after the first slash, or after the second one if it's an org.

**Comment by webpro** [comment]
The plugins return such specifiers, since they're not responsible for resolving them down to dependencies. Initially this was the case, hence the function name `findDependencies` in each plugin. However, the original specifiers should stay intact for file references to other packages in the same monorepo, which is handled later in the process.

Did you draw this comment from the changes I made or from actually running Knip? In the latter case I'll investigate.

**Comment by alecmev** [comment]
I see, thanks for the explanation! I get this:

```
Unused dependencies (1)
hastscript  packages/foo/package.json
```

I actually changed `jsxImportSource` to just `hastscript`, and still get this error, so it's something else.

**Comment by webpro** [comment]
The dependency is not reported as unused in the repro you posted if the only reference to `hastscript` or `hastscript/svg` is in a `@jsxImportSource` pragma. Maybe a monorepo thing, such as a duplicate dependency in root + package or something?

**Comment by alecmev** [comment]
Okay, I reproduced it, pushed to the same repo as above. The issue comes from `extends` in `tsconfig.json`. When I was looking at the logic before, I noticed that `compilerOptions` simply gets overwritten, rather than merged. I think that's the source, Knip just loses the JSX options.

**Comment by webpro** [comment]
Thanks Alec! Should be fixed in [v2.19.2](https://github.com/webpro/knip/releases/tag/2.19.2).

**Comment by alecmev** [comment]
Hi! I updated the reproduction to 2.29.0, and `hastscript` is still reported in `--production --strict`, unfortunately.

**Comment by webpro** [comment]
Wouldn't it be fair to say `hastscript` should be moved to `devDependencies` (just like `typescript` itself)? Since (at least in the repro) it's not referenced in production source files.

**Comment by alecmev** [comment]
Heya, I simplified the reproduction:

```ts
// index.tsx
export const foo = () => <g />;
```

```ts
// index.js
import { jsx as _jsx } from "hastscript/svg/jsx-runtime";
export var foo = function () { return _jsx("g", {}); };
```

`hastscript` is definitely a production dependency.

**Comment by alecmev** [comment]
On Knip 2.33.1, stuck on the following:

```ts
"ignoreDependencies": [] // Unused dependencies: hastscript
"ignoreDependencies": ["hastscript"] // Unused item in ignoreDependencies: hastscript
```

The configuration issue is a separate problem, I think (also had it with a private non-code monorepo package, resolved by dropping it as a dependency altogether), but yeah, not sure how to proceed now.

Do you disagree with my last comment?

**Comment by alecmev** [comment]
Thank you, this works!
